name = "tuff"
compatibility_date = "2024-08-14"
pages_build_output_dir = "apps/nexus/dist"

[[d1_databases]]
binding = "DB"
database_name = "tuff-nexus-prod"
database_id = "ebdeb7fc-74a4-4963-9bca-310a9aa0e4d6"

[[r2_buckets]]
binding = "R2"
bucket_name = "tuff-nexus-imgable-prod"
preview_bucket_name = "tuff-nexus-imgable-dev"

[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "tuff-nexus-dev"
database_id = "963cd4ae-2a63-408d-b3bc-fa5945f1e878"

[env.dev.vars]
NODE_OPTIONS = "--max-old-space-size=6144"
AUTH_SECRET = "change-me"
AUTH_ORIGIN = "http://localhost:3200"
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
LINUXDO_CLIENT_ID = ""
LINUXDO_CLIENT_SECRET = ""
LINUXDO_ISSUER = "https://connect.linux.do"
RESEND_API_KEY = ""
AUTH_EMAIL_FROM = "hello@tuff.app"

[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "tuff-nexus-imgable-dev"

[vars]
NODE_OPTIONS = "--max-old-space-size=6144"
AUTH_SECRET = "change-me"
AUTH_ORIGIN = "https://tuff.tagzxia.com"
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
LINUXDO_CLIENT_ID = ""
LINUXDO_CLIENT_SECRET = ""
LINUXDO_ISSUER = "https://connect.linux.do"
RESEND_API_KEY = ""
AUTH_EMAIL_FROM = "hello@tuff.app"
